# Generated by Django 6.1.1 on 2026-10-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('movie', 'Filme'), ('series', 'Serie')], default='movie', max_length=10)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_seasons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, to='catalog.genusmodel')),
            ],
        ),
    ]
