# Generated by Django 6.1.1 on 2026-10-02 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Quero ver'), ('watching', 'Assistindo'), ('done', 'Assistido'), ('dropped', 'Abandonado')], default='planned', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_episode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.titlemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'title'), name='one_entry_per_user_title'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 10)), _connector='OR'), name='rating_between_1_and_10')],
            },
        ),
    ]
